#Every time someone pushes or makes a pull request to main, spin up a temporary Ubuntu server, install Node.js, install my dependencies, and run the tests
name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16, 18]

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: install dependencies
        run: npm install

      - name: run tests
        run: npm test
